version: '3.7'

volumes:
  mongo_data:


services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  dashboard:
    build: .
    ports:
      - "8501:8501"
    container_name: life_expectancy_dashboard
    restart: always
    volumes:
      - .:/app

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888" # Jupyter Notebook-Standard-Port
    volumes:
      - ./notebooks:/home/jovyan/work # Notebook-Daten werden auf deinem lokalen System gespeichert
      - ./quelldateien:/home/jovyan/files # Mount local folder for Excel and CSV files
    environment:
      - JUPYTER_TOKEN=mytoken # Authentifizierungstoken für Jupyter Notebook
    depends_on:
      - mongodb
    command: >
      start-notebook.sh --NotebookApp.token='mytoken'
      && pip install pycountry
  

  # Stop the container
  #docker stop life_expectancy_dashboard

  # Remove the container
  #docker rm life_expectancy_dashboard

  #docker rm -f life_expectancy_dashboard

  # Stop and remove existing containers and volumes
  #docker-compose down -v

  # Remove any existing images
  #docker system prune -f

  # Build and start the containers
  #docker-compose up -d --build