version: '3.7'

volumes:
  mongo_data:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  dashboard:
    build: .
    ports:
      - "8501:8501"
    container_name: life_expectancy_dashboard
    restart: always
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./quelldateien:/home/jovyan/files
    environment:
      - JUPYTER_TOKEN=mytoken
    depends_on:
      - mongodb
    command: >
      start-notebook.sh --NotebookApp.token='mytoken'
      && pip install pycountry

  # Stop the container
  #docker stop life_expectancy_dashboard

  # Remove the container
  #docker rm life_expectancy_dashboard

  #docker rm -f life_expectancy_dashboard

  # Stop and remove existing containers and volumes
  #docker-compose down -v

  # Remove any existing images
  #docker system prune -f

  # Build and start the containers
  #docker-compose up -d --build

  # Start all services in background (Jupyter, MongoDB, Dashboard):
  # docker-compose up -d

  # Launch the updated Streamlit dashboard with pie chart + MapReduce:
  # streamlit run life_expectancy_dashboard_with_pie_mapreduce.py